### ISSUE TITLE
Separate the tool from the content

### ISSUE THREAD

**Issue by tfoote** [audrow/yatm#375]
It would be great to separate the tool from the content.

In particular as we look at using this for more use cases, such as gazebo and ROS it doesn't really make sense to have the requirements in the tool's repository. Instead the tool should take an argument for a path to the requirements and configuration and we can maintain those in a separate repo. (Potentially even the one that will have all the issues created against it) That way separate projects content can have different lifecycles etc.

**Comment by Yadunund** [comment]
Sounds good!

**Comment by Yadunund** [comment]
Completed via #404
